### ISSUE TITLE
implement sign up endpoint

### ISSUE THREAD

**Issue by isa-gol** [it-for-us/todo#2]
**as backend**
**i want** to sign up to system by using username, email and password
**So that** the user should be able to sign up with username. email and password  
Usa encrypted password in db
**Sample request**
```
{
    "userName": "user name",
    "email": "email@email.com",
    "password": "123456"
}
```

**Sample response**
```
HTTP/1.1 200 OK
Content-Type: application/json 
{
    “id”: “f750afe4-65c9-11ed-9022-0242ac120002”,
    "userName": "user name",
    "email": "email@email.com"
}

```

Acceptance criteria 1
Given sign up request sent to the sign up endpoint
When email, username and password is valid
Then backend must return created user data with user id
```
HTTP/1.1 200 OK
Content-Type: application/json 
{
    “id”: “f750afe4-65c9-11ed-9022-0242ac120002”,
    "userName": "user name",
    "email": "email@email.com"
}
```

Acceptance criteria 2
**Given** sign up request sent to the sign up endpoint
**When** email and password is valid and username is null
**Then** backend must return created user data with generated username

Username will be generated like:
**Email**: abc@email.com
**Username**: abc124354
We will add random 6 digits to the part of email before @

**Sample request**
```
{
    "userName": null,
    "email": "email@email.com",
    "password": "123456"
}
```

**Sample response:**
```
HTTP/1.1 200 OK
Content-Type: application/json 
{
    “id”: “f750afe4-65c9-11ed-9022-0242ac120002”,
    "userName": "email002324",
    "email": "email@email.com"
}
```

Acceptance criteria3
Given sign in request sent to the sign up endpoint
When email already exist
Then backend must return forbidden request exception

```
HTTP/1.1 403 Forbidden Request
Content-Type: application/json  
{ 
  "message":"user already exist", 
  "code": 403
} 
```

Acceptance criteria4
**Given** sign up request sent to the sign up endpoint
**When** username, email or password is incorrect format
**Then** backend must return bad request exception
email must be in email format
username cannot be empty
Password should be at least 8 chracters
```
HTTP/1.1 400 Bad Request
Content-Type: application/json  
{ 
  "message":"bad request", 
  "code": 400
} 
```

**Comment by yumerchalashkan** [comment]
it finished. i sent it.
