### ISSUE TITLE
Register Page

### ISSUE THREAD

**Issue by mersahin** [it-for-us/todo#26]
**as backend**
**i want** to sign up to system by using username, email and password
**So that** the user should be able to sign up with username. email and password  

Bir Register sayfasi olusturulmali
bu kayit sayfasina menüdeki bir link ile veya anasafyadaki bir buton ile erisilebilmeli.
bir form tasarlanmali
formda su bilgiler istenilmeli
email
isim soyism
sifre
Kullanim kosullarinin onaylanamasi

Asagidaki sekilde istek backende gönderilmeli
/signup

**Sample request**
```
{
    "userName": "user name",
    "email": "email@email.com",
    "password": "123456"
}
```

**Sample response**
```
HTTP/1.1 200 OK
Content-Type: application/json 
{
    “id”: “f750afe4-65c9-11ed-9022-0242ac120002”,
    "userName": "user name",
    "email": "email@email.com"
}

```

Acceptance criteria 1
Gönderim öncesi Email Username Password bilgileri dogrulanmali.

```
HTTP/1.1 200 OK
Content-Type: application/json 
{
    “id”: “f750afe4-65c9-11ed-9022-0242ac120002”,
    "userName": "user name",
    "email": "email@email.com"
}
```

Acceptance criteria 2
Username zorunlu alan olarak gönderilmesede kayit yapilabilmeli.

Username will be generated like:
**Email**: abc@email.com
**Username**: abc124354
We will add random 6 digits to the part of email before @

**Sample request**
```
{
    "userName": null,
    "email": "email@email.com",
    "password": "123456"
}
```

**Sample response:**
```
HTTP/1.1 200 OK
Content-Type: application/json 
{
    “id”: “f750afe4-65c9-11ed-9022-0242ac120002”,
    "userName": "email002324",
    "email": "email@email.com"
}
```

Acceptance criteria3
Zaten kayitli bir maille kayit istegi gönderildigiinde kullanici bir mata mesajiyla bilgilendirilmeli.

```
HTTP/1.1 403 Forbidden Request
Content-Type: application/json  
{ 
  "message":"user already exist", 
  "code": 403
} 
```

Acceptance criteria4

Asagidaki Validation kurallari uygulanmali;

email must be in email format
Password should be at least 8 characters

aksi halde uyari mesaji verilmeli

```
HTTP/1.1 400 Bad Request
Content-Type: application/json  
{ 
  "message":"bad request", 
  "code": 400
} 
```

![Image](https://user-images.githubusercontent.com/3853524/205462982-7ced1a22-0bd0-4e47-bfb1-7770d78d86e8.png)

**Comment by aliturkes** [comment]
@mersahin  @kemaltt  

Register sayfasi ile ilgili testlere devam edebilmek icin sanirim artik beckend'e bagli olmak gerekiyor yoksa ayni mail ile birden fazla kayit olusturamama yada olusuturulan kayitli mail veya username ile login olma gibi fonksyonlarin gecip gecmedigni test edemeyiz.

**Comment by kemaltt** [comment]
@aliturkes abi mevcut kullanıcı var mı yok mu sorgulama yapabilirsin, mevcut bir kullanıcı varmış gibi tasarladı
