### ISSUE TITLE
React Project initialize

### ISSUE THREAD

**Issue by mersahin** [it-for-us/todo#28]
```
npx create-react-app frontend
cd frontend
npm start
```

proje init edilip /todo/frontend  altina push edilmeli.

**Comment by mersahin** [comment]
commit görünce in progress olduugna kanaat getirdim (:

**Comment by kemaltt** [comment]
Dosya yapisi nasil kurulmali onu konusmadik sanirim.Örnegin src dosyasinin icinde components pages, yada assets in altinda mi olmali

**Comment by harunaltunhr** [comment]
@kemaltt 
@mersahin 
@Osman-Ozturk 
Onerim;
Src'nin icinde;
1 Css dosyasi
App.js
Index.js
Components & Pages Klasorleri.

**Comment by kemaltt** [comment]
@harunaltunhr @mersahin @Osman-Ozturk benim icin ok. Harun bey in eklediklerini pull edemiyorum, hepimizin ok mi vermesi lazim ben kurcalarken aprove ettim ama bisey degismedi
