### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by mersahin** [it-for-us/todo#30]
#28 
Sol tarafta Logo ortada menü sag tarafta Login olunmus ise Kullanici Adi konulabilir

**Comment by kemaltt** [comment]
@harunaltunhr abi logo yu beyaz mi yapsak :)

**Comment by harunaltunhr** [comment]
@kemaltt 
https://www.canva.com/design/DAFU7w_ggtU/l1PpX10nnAhtWfRXnyZ2ew/view?utm_content=DAFU7w_ggtU&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink
(Arkaplan olmayacak)
Bu nasil?

**Comment by harunaltunhr** [comment]
![image](https://user-images.githubusercontent.com/62182810/208170198-29e7256f-3911-4287-b673-4edbf2384909.png)

**Comment by harunaltunhr** [comment]
![image](https://user-images.githubusercontent.com/62182810/208170302-3930806f-5c73-4a98-b910-ba7f19d1648f.png)

**Comment by kemaltt** [comment]
👍
