### ISSUE TITLE
Footer Komponent

### ISSUE THREAD

**Issue by mersahin** [it-for-us/todo#33]
Footer Her sayfanin alt kisminda görünecek

- Policy Sayfasi Linki
- Contact Sayfasi Linki
-

**Comment by harunaltunhr** [comment]
Sosyal Medya hesaplari eklenebilir diye dusundum. Ne dersiniz?

**Comment by Osman-Ozturk** [comment]
Bence gayet güzel olur

**Comment by kemaltt** [comment]
![Image](https://user-images.githubusercontent.com/90035121/206737025-189164d1-a9dd-42ae-8c50-4f82999a772f.png)



![Image](https://user-images.githubusercontent.com/90035121/206737840-5904e1d8-8b5f-4948-b4e5-1409f28cf6d8.png)




@harunaltunhr  abi footer in height ini azaltsak iyi olur gibi Login ve register page te butonlar görünmüyor
