### ISSUE TITLE
Forgot password (Sifremi unuttum)

### ISSUE THREAD

**Issue by mersahin** [it-for-us/todo#36]
# User Story
As a user, I can reset my password if I’ve forgotten it
- The story is considered done when after clicking on “Forgot password”, I receive an email with a link to the “Settings” page to change my password
## Validation
- As a user, I can see an error message if something with creating
an account or signing in went wrong
- The story is considered done when a visually distinguishable message is shown to the user, together with explanation what is incorrect (e.g. email missing an “@” symbol)

# Requirement
- sifresini unutan User mail yoluyla sifresini sifirlayabilmeli

# Acceptance Criteria
- anasayfadaki menüde sifremi unuttum (CTA: call to action) olacak
- CTA tiklaninica kullanmiciya email adresi sorulacak
- email adresine bir link gelecek
- linke tiklaninca yeni sifresini girebilecegi bir ekranla karsilasacak
- o ekranda sifresini girince artik o sifre onun yeni sifresi olacak.

#Ready of Done (RoD)
- Sifre basarili sekilde degistirilebilmeli.

![Image](https://user-images.githubusercontent.com/3853524/205462968-dbda86e8-b417-47e2-8a7b-656e7ce23ef0.png)

**Comment by aliturkes** [comment]
@kemaltt OK Done'a atiyorum
