### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by mersahin** [it-for-us/todo#51]
- hangi UI kullanilacak
-- material UI
--tailwind
-- Bootstrap5 
- SRC klasör yapisi
- gereksiz dosyalarin silinmesi
- projenin adinin degistirilmesi
- vs code formatter olarak Prettier kullanilmali
-------------------------

├─ src/
│  ├─ assets/
│  │  ├─ scss/
│  │  │  ├─ base/
│  │  │  │  ├─ _mixins.scss
│  │  │  │  ├─ _variables.scss
│  │  │  │  ├─ _functions.scss
│  │  │  │  ├─ _typography.scss
│  │  │  ├─ components/
│  │  │  ├─ layout/
│  │  │  ├─ pages/
│  │  │  ├─ main.scss
│  │  ├─ i18n/
│  │  ├─ js/
│  │  │  ├─ main.js
│  │  ├─ css/
│  │  │  ├─ main.css
│  ├─ hooks/
│  ├─ modules/
│  ├─ pages/
│  ├─ components/
│  ├─ index.css
│  ├─ index.js
├─ .gitignore
├─ package.json
├─ README.md
---------------------------

**Comment by rdvnbyr** [comment]
@kemaltt bakarsin..

**Comment by mersahin** [comment]
çok şık duruyor. yeni dosya yapısı (:

**Comment by kemaltt** [comment]
@mersahin    @rdvnbyr es sieht übersichtlich aus. kannst du bitte #130  genehmigen(aprov). dann werde ich für diesen neue request senden

**Comment by rdvnbyr** [comment]
Ok , 👍
