### ISSUE TITLE
Welcome ToDo 2 Page

### ISSUE THREAD

**Issue by harunaltunhr** [it-for-us/todo#83]
3.2. Welcome TODO -2 ( Login olduktan sonra) : Kullanıcı hesabını oluşturduktan sonra ilk
Workspace ve Board alanlarını oluşturmuştu. Bu nedenle tekrar login olduğunda karşısına çıkacak ilk
ekran yine Welcome TODO ekranı olacaktır fakat bu sefer önceden oluşturduğu ilk Workspace alanını
görmelidir

![Image](https://user-images.githubusercontent.com/62182810/208267347-d0e668f0-052f-46e3-9e52-d7212bc51c9a.png)

**Comment by kemaltt** [comment]
@harunaltunhr abi bu sayfayi page olarak degilde home page icinde bir component gibi yapmak daha mantikli gibi, en azindan ben öyle anladim , ben simdilik components klasörü altinda workSpace adli component olarak yapiyorum sonrasi duruma göre göre page e de dönüstürürüz

**Comment by harunaltunhr** [comment]
@kemaltt Abi mantikli. Benim de sorum su; Burada **Header farkli** (benim yaptigim sayfada da farkli). Cozum olarak 2. bir header olusturup bunlari direk componentlerin icine mi eklemek gerek acaba? Ya da baska bir cozum var mi?

**Comment by harunaltunhr** [comment]
@kemaltt  Ayni sekilde footer'in gorunmemesinin yolu da bu sanirim. App.js de olursa her seferinde karsilasacagiz kendileri ile

**Comment by kemaltt** [comment]
@harunaltunhr aynen ,farkli header lar olusturmak gerekiyor , footer da app js den alip sadece home a koymak gerekiyor
